/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package simple.tetris;
import simple.tetris.GamePanel; 
import simple.tetris.TetrisGame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Abid
 */
public class MainUI extends javax.swing.JFrame {
    
    private Timer gameTimer;
    private TetrisGame activeGame;
    /**
     * Creates new form MainUI
     */
    public MainUI() {
        
        activeGame = new TetrisGame(); // Initialize here
        initComponents();              // NetBeans generated code

        this.setLocationRelativeTo(null); 
        this.setFocusable(true);
        this.requestFocusInWindow();
        this.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                switch(evt.getKeyCode()) {
                    case java.awt.event.KeyEvent.VK_LEFT: activeGame.attemptMove(-1, 0); break;
                    case java.awt.event.KeyEvent.VK_RIGHT: activeGame.attemptMove(1, 0); break;
                    case java.awt.event.KeyEvent.VK_DOWN: activeGame.update(); break;
                    case java.awt.event.KeyEvent.VK_UP: activeGame.attemptRotate(); break;
                    case java.awt.event.KeyEvent.VK_SPACE: activeGame.hardDrop(); break;
                    case java.awt.event.KeyEvent.VK_P: activeGame.togglePause();repaint();break;
                    case java.awt.event.KeyEvent.VK_E: activeGame.togglePause();repaint();break;
                }
                repaint(); // Refresh the screen
            }
        });

        gameTimer = new Timer(500, e -> {
            // Only update the game if NOT paused and NOT game over
            if (!activeGame.getGameState() && !activeGame.isPaused()) {
                activeGame.update();
                refreshUI();
            } else {
                // Still repaint so the overlay shows up immediately
                repaint();
            }
        });
        gameTimer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        something = new javax.swing.JPanel();
        gameBG = new javax.swing.JPanel();
        gameWindow = new GamePanel(activeGame);
        lblScore = new javax.swing.JLabel();
        jPanel2 = new NextPiecePanel(activeGame);
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout somethingLayout = new javax.swing.GroupLayout(something);
        something.setLayout(somethingLayout);
        somethingLayout.setHorizontalGroup(
            somethingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        somethingLayout.setVerticalGroup(
            somethingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );

        gameBG.setBackground(new java.awt.Color(153, 153, 255));
        gameBG.setBorder(new javax.swing.border.MatteBorder(null));

        gameWindow.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gameWindow.setForeground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout gameWindowLayout = new javax.swing.GroupLayout(gameWindow);
        gameWindow.setLayout(gameWindowLayout);
        gameWindowLayout.setHorizontalGroup(
            gameWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );
        gameWindowLayout.setVerticalGroup(
            gameWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );

        lblScore.setBackground(new java.awt.Color(235, 188, 226));
        lblScore.setFont(new java.awt.Font("sansserif", 3, 18)); // NOI18N
        lblScore.setForeground(new java.awt.Color(255, 255, 255));
        lblScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScore.setText("SCORE: ");
        lblScore.setToolTipText("");

        jPanel2.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 87, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Next Piece");

        javax.swing.GroupLayout gameBGLayout = new javax.swing.GroupLayout(gameBG);
        gameBG.setLayout(gameBGLayout);
        gameBGLayout.setHorizontalGroup(
            gameBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameBGLayout.createSequentialGroup()
                .addGroup(gameBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameBGLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(gameWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(gameBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(gameBGLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(lblScore, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        gameBGLayout.setVerticalGroup(
            gameBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameBGLayout.createSequentialGroup()
                .addGroup(gameBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameBGLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameBGLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(gameWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblScore, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gameBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(something, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(something, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(gameBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
           // logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainUI().setVisible(true));
    }

    
    /**
 * Updates all visual components at once.
 * Call this whenever the game state changes.
 */
private void refreshUI() {
    // 1. Update the score label
    lblScore.setText("SCORE: " + activeGame.getScore());
    
    // 2. Redraw the main game board
    gameWindow.repaint(); 
    
    // 3. Redraw the next piece preview
    jPanel2.repaint();    
    
    // 4. Force the main frame to update
    this.repaint();
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel gameBG;
    private javax.swing.JPanel gameWindow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblScore;
    private javax.swing.JPanel something;
    // End of variables declaration//GEN-END:variables
}
